- author_avatar_url: assets\173bb31c158e66d28fb7004e2145c997-58F17.png
  author_id: '1294460037267193913'
  author_name: chrisinvancouver
  author_nickname: ChrisInVancouver
  content: "I\u2019d like to join the Content Brigade to help with proofreading and\
    \ research. I have more than 20 years of professional writing and editing experience,\
    \ and my current job also involves conducting extensive research on complex topics.\
    \ I was unable to complete the application because it required me to submit a\
    \ link to a social media account for content examples, and I don\u2019t use social\
    \ media. My interest in joining the team is to use my technical skills to assist\
    \ the content developers."
  id: '1294472953534353452'
  ref_to: null
  timestamp: '2024-10-12T01:33:22.267+00:00'
  type: Default
- author_avatar_url: assets\40429fdc04bc158542943bec1abc286b-0D361.png
  author_id: '996999701461225473'
  author_name: mrschmidty1234
  author_nickname: Mr.Schmidty
  content: Hey there!! If you try applying again try just typing in N/A for that question
    or attaching a resume to show your vast experience!!!
  id: '1294523572051513354'
  ref_to: null
  timestamp: '2024-10-12T04:54:30.662+00:00'
  type: Default
- author_avatar_url: assets\41ef520387924aa4413513eda28784df-34D82.png
  author_id: '782870341445353522'
  author_name: jayrio76
  author_nickname: Jay E  (TX)  OE Mod
  content: Great, yes, I had a similar question. I will do the same. It will be great
    have folks like <@1294460037267193913>.  Thanks, <@996999701461225473>.
  id: '1295067317994262608'
  ref_to: null
  timestamp: '2024-10-13T16:55:09.797+00:00'
  type: Default
