- author_avatar_url: assets\8569adcbd36c70a7578c017bf5604ea5-FE355.png
  author_id: '1288293420162613380'
  author_name: sublimeromantic
  author_nickname: Holly
  content: "Hi! I submitted a form to volunteer for the content brigade. I didn\u2019\
    t get a confirmation email, so I just wanted to check it was received. \U0001F642\
    \ If you need more info, my dms should be open."
  id: '1291230461204369491'
  ref_to: null
  timestamp: '2024-10-03T02:48:51.853+00:00'
  type: Default
- author_avatar_url: assets\28a90c77b5793d80eb62484a43c66748-D8837.png
  author_id: '568257600228032512'
  author_name: carb.on
  author_nickname: "Carolyn B [CA] \u2022 Lead Mod"
  content: Hello <@1288293420162613380> did you submit your form recently? or was
    it more than two weeks ago? Content brigade changed the application process about
    two weeks ago and asked folks to re-apply. with this form https://txt.democrats.org/CreatorTeamApply
    if that is the form you used, I suggest being patient and they should reach or
    submit the form again to bring it to their attention.
  id: '1291252186017431634'
  ref_to: '1291230461204369491'
  timestamp: '2024-10-03T04:15:11.452+00:00'
  type: Reply
