- author_avatar_url: assets\17fb4b0839e396d5ffc030c4e3be8560-1FCAC.png
  author_id: '1274751606142931149'
  author_name: lauraschairbaum
  author_nickname: Laura Scha.[KC Chat Captain] IN
  content: "Is there a way to change the Discord setting so I don't see all the replies\
    \ to a comment? I'm feeling a bit overwhelmed by all the replies to comments on\
    \ the feeds \U0001F979"
  id: '1277425828162043956'
  ref_to: null
  timestamp: '2024-08-26T00:34:10.858+00:00'
  type: Default
- author_avatar_url: assets\28a90c77b5793d80eb62484a43c66748-D8837.png
  author_id: '568257600228032512'
  author_name: carb.on
  author_nickname: "Carolyn B [CA] \u2022 Lead Mod"
  content: Hi <@1274751606142931149> I 100% appreciate your overwhelm. We have a little
    video to help you manage Discord, and if video doesn't resonate with you I can
    text you though the steps. https://youtu.be/cA32MMsN61g
  id: '1277426998746021918'
  ref_to: null
  timestamp: '2024-08-26T00:38:49.947+00:00'
  type: Default
- author_avatar_url: assets\17fb4b0839e396d5ffc030c4e3be8560-1FCAC.png
  author_id: '1274751606142931149'
  author_name: lauraschairbaum
  author_nickname: Laura Scha.[KC Chat Captain] IN
  content: "@Carolyn B I really appreciate it! I'll watch it and let you know \U0001F601"
  id: '1277427566571032657'
  ref_to: null
  timestamp: '2024-08-26T00:41:05.327+00:00'
  type: Default
- author_avatar_url: assets\3-FB033.png
  author_id: '1270181135036452895'
  author_name: veenom2025
  author_nickname: Veenom2025
  content: "Wow!!!  I saw my post & photo listed\u2026. I\u2019m loving Discord &\
    \ REACH!  I\u2019ll be heading to the campaign office this week to volunteer!!!"
  id: '1277662364463796295'
  ref_to: null
  timestamp: '2024-08-26T16:14:05.507+00:00'
  type: Default
- author_avatar_url: assets\8b706a86e5f9b8dcaaa950a7500b77b8-E1341.png
  author_id: '957714233217409174'
  author_name: opheliawild
  author_nickname: "Ophelia W \u2022 Lead Mod"
  content: 'We also have this: <#1242801792018940005> which has notification setting
    instructions and tips.'
  id: '1277674417903632506'
  ref_to: null
  timestamp: '2024-08-26T17:01:59.271+00:00'
  type: Default
